language: node_js

sudo: false
dist: trusty

git:
  depth: 3

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

notifications:
  email: false
  slack:
    secure: qorwdTu1od1QSvbwiR1JX60czaUpPFgTacBr0WgX+KJaLABjkc3+2j+rYVpbZu8Gwb5zU+IEApp8QSySRkETubqMTou7AFAVwbgvf3xBcj0/9KgKJLmHkD102CzfqMo6Aq7KCtzhBpzMmAPmp7MxEv3vhSNDUsOKcGXO0RdT4qzOhfHo6xQ9daxUyoQxaDMOsPZSm9hiuXWzFdgD/IleEzpls3NBCR1S4xBVmppaRvLppbmW9oaM2LoJ9rbr0MvJnF2gRXK7hUjoX9G7t0N4FwsNhKpIFeAyhiIicIKVQFdDLNbRdwaUZ5z8LpjjAEUr4lbruXfPIOKcFpsAmeOn7Pw67WNp6NwLwd1s4fH7OjM8cqqfpJue01t4m6fLxsTq4KZA+NRn4bSEnijBSR435XFfkT391AQ+N/mWjQidoLvR4fadzq5wyvGXJ0TacIGkampjWuqNQupTVDdndFZbvQLC0dpRXJRb0KdIxi4a3blaFTclO76Ds2hVh8wM8Z+v3uFaBOkAg5W1HyvIZ6IPwUSG4X1q04q8jJjAkuMmmDBvuIgz2aKieCmIIwTMo9GP4mVmfK+4QB8aLu++kTQDFn4QfOFCsmFej4m8q8BIaywVl74AzS2LAqaRZtTAzKm4uJ6rrTGs/b4cyOYHanNUNMZkzWq2aVIgH3HUvhYg8OQ=

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"

cache: yarn

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: test
    if: branch = master and tag IS blank and type IN (pull_request, api)

before_script:
  - composer setup

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.3'
      script: composer phpcs
    - stage: check
      language: php
      php: '7.3'
      script: composer phpmd

    - stage: test
      language: php
      php: '7.3'
      script: composer phpunit
    - stage: test
      language: php
      php: '7.4'
      script: composer phpunit
